services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args: ["PORT=${PORT}"]
    env_file: [".env"]
    ports: ["127.0.0.1:${PORT}:${PORT}"]
    restart: always
    depends_on: [app]
