services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args: ["APP_PORT=${APP_PORT}"]
    ports: ["127.0.0.1:${APP_PORT}:${APP_PORT}"]
    env_file: [.env]
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${PGPORT}/${POSTGRES_USER}?schema=public"
    restart: always
    depends_on: [db, migrations]
  migrations:
    image: node:20.17-alpine
    env_file: [.env]
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${PGPORT}/${POSTGRES_USER}?schema=public"
    restart: on-failure
    working_dir: /migrate
    volumes: [./prisma/:/migrate/prisma]
    command: npx prisma migrate deploy
    depends_on: [db]
  db:
    image: postgres:16.2
    restart: always
    env_file: [.env]
    ports: ["127.0.0.1:${PGPORT}:${PGPORT}"]
    volumes: ["pgdata:/var/lib/postgresql/data"]

volumes:
  pgdata:
